// src/ui/icon.tsx - Centralized Icon System with lucide-react
import React from 'react';
import type { LucideIcon } from 'lucide-react';
import {
    User,
    Users,
    Calendar,
    Clock,
    Phone,
    MessageCircle,
    Search,
    Check,
    X,
    Plus,
    Minus,
    ChevronLeft,
    ChevronRight,
    ChevronDown,
    ChevronUp,
    ArrowRight,
    ArrowLeft,
    ArrowUpRight,
    ArrowDownRight,
    Star,
    Bell,
    Tag,
    CreditCard,
    Wallet,
    Settings,
    Home,
    Menu,
    LogOut,
    Sparkles,
    Gift,
    Crown,
    AlertCircle,
    Info,
    Filter,
    Trash2,
    Edit3,
    Eye,
    EyeOff,
    Image,
    Upload,
    Download,
    MoreHorizontal,
    MoreVertical,
    Hash,
    Megaphone,
    BarChart3,
    PieChart,
    ClipboardList,
    Trophy,
    Scissors,
    DollarSign,
    Receipt,
    Printer,
    FileText,
    Sheet,
    Mail,
    MapPin,
    Zap,
    Heart,
    Share2,
    Copy,
    ExternalLink,
    RefreshCw,
    Loader2,
    CheckCircle2,
    XCircle,
    AlertTriangle,
    HelpCircle,
    Lock,
    Unlock,
    ShieldCheck,
    Key,
    QrCode,
    Smartphone,
    Wifi,
    WifiOff,
    Volume2,
    VolumeX,
    Sun,
    Moon,
    Globe,
    Camera,
    Video,
    Mic,
    MicOff,
    Play,
    Pause,
    SkipForward,
    SkipBack,
    Rewind,
    FastForward,
    Repeat,
    Shuffle,
    List,
    Grid3X3,
    LayoutGrid,
    Columns,
    Rows,
    SlidersHorizontal,
    Palette,
    Droplet,
    Flame,
    Snowflake,
    CloudRain,
    Wind,
    Thermometer,
    Building2,
    Store,
    Package,
    ShoppingCart,
    ShoppingBag,
    Percent,
    TrendingUp,
    TrendingDown,
    Activity,
    Target,
    Award,
    Medal,
    Bookmark,
    BookmarkCheck,
    Flag,
    Pin,
    Send,
    Reply,
    Forward,
    Archive,
    Inbox,
    FolderOpen,
    File,
    FileCheck,
    FilePlus,
    FileX,
    Link,
    Unlink,
    Paperclip,
    Grip,
    GripVertical,
    Move,
    Maximize,
    Minimize,
    Expand,
    Shrink,
    ZoomIn,
    ZoomOut,
    RotateCw,
    RotateCcw,
    FlipHorizontal,
    FlipVertical,
    Layers,
    Box,
    Circle,
    Square,
    Triangle,
    Hexagon,
    Octagon,
    Star as StarIcon,
    PiggyBank,
    Banknote,
    Coins,
    Calculator,
    CalendarCheck,
    CalendarX,
    CalendarPlus,
    CalendarClock,
    UserPlus,
    UserMinus,
    UserCheck,
    UserX,
    UsersRound,
    Contact,
    Handshake,
    ThumbsUp,
    ThumbsDown,
    MessageSquare,
    MessagesSquare
} from 'lucide-react';

// Icon name type for type-safety
export type IconName =
    | 'user' | 'users' | 'users-round' | 'user-plus' | 'user-minus' | 'user-check' | 'user-x'
    | 'calendar' | 'calendar-check' | 'calendar-x' | 'calendar-plus' | 'calendar-clock'
    | 'clock' | 'phone' | 'message' | 'messages' | 'message-square'
    | 'search' | 'check' | 'x' | 'plus' | 'minus'
    | 'chevron-left' | 'chevron-right' | 'chevron-down' | 'chevron-up'
    | 'arrow-right' | 'arrow-left' | 'arrow-up-right' | 'arrow-down-right'
    | 'star' | 'bell' | 'tag' | 'credit-card' | 'wallet'
    | 'settings' | 'home' | 'menu' | 'logout'
    | 'sparkles' | 'gift' | 'crown' | 'alert' | 'info'
    | 'filter' | 'trash' | 'edit' | 'eye' | 'eye-off'
    | 'image' | 'upload' | 'download' | 'more' | 'more-vertical'
    | 'hash' | 'megaphone' | 'bar-chart' | 'pie-chart' | 'clipboard'
    | 'trophy' | 'scissors' | 'dollar' | 'receipt' | 'printer' | 'file-text' | 'sheet'
    | 'mail' | 'map-pin' | 'zap' | 'heart' | 'share' | 'copy' | 'external-link'
    | 'refresh' | 'loader' | 'check-circle' | 'x-circle' | 'alert-triangle' | 'help-circle'
    | 'lock' | 'unlock' | 'shield-check' | 'key' | 'qr-code' | 'smartphone'
    | 'wifi' | 'wifi-off' | 'volume' | 'volume-off' | 'sun' | 'moon' | 'globe'
    | 'camera' | 'video' | 'mic' | 'mic-off'
    | 'play' | 'pause' | 'skip-forward' | 'skip-back' | 'rewind' | 'fast-forward' | 'repeat' | 'shuffle'
    | 'list' | 'grid' | 'layout-grid' | 'columns' | 'rows' | 'sliders' | 'palette'
    | 'droplet' | 'flame' | 'snowflake' | 'cloud-rain' | 'wind' | 'thermometer'
    | 'building' | 'store' | 'package' | 'shopping-cart' | 'shopping-bag' | 'percent'
    | 'trending-up' | 'trending-down' | 'activity' | 'target' | 'award' | 'medal'
    | 'bookmark' | 'bookmark-check' | 'flag' | 'pin' | 'send' | 'reply' | 'forward'
    | 'archive' | 'inbox' | 'folder' | 'file' | 'file-check' | 'file-plus' | 'file-x'
    | 'link' | 'unlink' | 'paperclip' | 'grip' | 'grip-vertical' | 'move'
    | 'maximize' | 'minimize' | 'expand' | 'shrink' | 'zoom-in' | 'zoom-out'
    | 'rotate-cw' | 'rotate-ccw' | 'flip-h' | 'flip-v' | 'layers' | 'box'
    | 'circle' | 'square' | 'triangle' | 'hexagon' | 'octagon'
    | 'piggy-bank' | 'banknote' | 'coins' | 'calculator'
    | 'contact' | 'handshake' | 'thumbs-up' | 'thumbs-down';

// Icon mapping
const ICONS: Record<IconName, LucideIcon> = {
    'user': User,
    'users': Users,
    'users-round': UsersRound,
    'user-plus': UserPlus,
    'user-minus': UserMinus,
    'user-check': UserCheck,
    'user-x': UserX,
    'calendar': Calendar,
    'calendar-check': CalendarCheck,
    'calendar-x': CalendarX,
    'calendar-plus': CalendarPlus,
    'calendar-clock': CalendarClock,
    'clock': Clock,
    'phone': Phone,
    'message': MessageCircle,
    'messages': MessagesSquare,
    'message-square': MessageSquare,
    'search': Search,
    'check': Check,
    'x': X,
    'plus': Plus,
    'minus': Minus,
    'chevron-left': ChevronLeft,
    'chevron-right': ChevronRight,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    'arrow-right': ArrowRight,
    'arrow-left': ArrowLeft,
    'arrow-up-right': ArrowUpRight,
    'arrow-down-right': ArrowDownRight,
    'star': Star,
    'bell': Bell,
    'tag': Tag,
    'credit-card': CreditCard,
    'wallet': Wallet,
    'settings': Settings,
    'home': Home,
    'menu': Menu,
    'logout': LogOut,
    'sparkles': Sparkles,
    'gift': Gift,
    'crown': Crown,
    'alert': AlertCircle,
    'info': Info,
    'filter': Filter,
    'trash': Trash2,
    'edit': Edit3,
    'eye': Eye,
    'eye-off': EyeOff,
    'image': Image,
    'upload': Upload,
    'download': Download,
    'more': MoreHorizontal,
    'more-vertical': MoreVertical,
    'hash': Hash,
    'megaphone': Megaphone,
    'bar-chart': BarChart3,
    'pie-chart': PieChart,
    'clipboard': ClipboardList,
    'trophy': Trophy,
    'scissors': Scissors,
    'dollar': DollarSign,
    'receipt': Receipt,
    'printer': Printer,
    'file-text': FileText,
    'sheet': Sheet,
    'mail': Mail,
    'map-pin': MapPin,
    'zap': Zap,
    'heart': Heart,
    'share': Share2,
    'copy': Copy,
    'external-link': ExternalLink,
    'refresh': RefreshCw,
    'loader': Loader2,
    'check-circle': CheckCircle2,
    'x-circle': XCircle,
    'alert-triangle': AlertTriangle,
    'help-circle': HelpCircle,
    'lock': Lock,
    'unlock': Unlock,
    'shield-check': ShieldCheck,
    'key': Key,
    'qr-code': QrCode,
    'smartphone': Smartphone,
    'wifi': Wifi,
    'wifi-off': WifiOff,
    'volume': Volume2,
    'volume-off': VolumeX,
    'sun': Sun,
    'moon': Moon,
    'globe': Globe,
    'camera': Camera,
    'video': Video,
    'mic': Mic,
    'mic-off': MicOff,
    'play': Play,
    'pause': Pause,
    'skip-forward': SkipForward,
    'skip-back': SkipBack,
    'rewind': Rewind,
    'fast-forward': FastForward,
    'repeat': Repeat,
    'shuffle': Shuffle,
    'list': List,
    'grid': Grid3X3,
    'layout-grid': LayoutGrid,
    'columns': Columns,
    'rows': Rows,
    'sliders': SlidersHorizontal,
    'palette': Palette,
    'droplet': Droplet,
    'flame': Flame,
    'snowflake': Snowflake,
    'cloud-rain': CloudRain,
    'wind': Wind,
    'thermometer': Thermometer,
    'building': Building2,
    'store': Store,
    'package': Package,
    'shopping-cart': ShoppingCart,
    'shopping-bag': ShoppingBag,
    'percent': Percent,
    'trending-up': TrendingUp,
    'trending-down': TrendingDown,
    'activity': Activity,
    'target': Target,
    'award': Award,
    'medal': Medal,
    'bookmark': Bookmark,
    'bookmark-check': BookmarkCheck,
    'flag': Flag,
    'pin': Pin,
    'send': Send,
    'reply': Reply,
    'forward': Forward,
    'archive': Archive,
    'inbox': Inbox,
    'folder': FolderOpen,
    'file': File,
    'file-check': FileCheck,
    'file-plus': FilePlus,
    'file-x': FileX,
    'link': Link,
    'unlink': Unlink,
    'paperclip': Paperclip,
    'grip': Grip,
    'grip-vertical': GripVertical,
    'move': Move,
    'maximize': Maximize,
    'minimize': Minimize,
    'expand': Expand,
    'shrink': Shrink,
    'zoom-in': ZoomIn,
    'zoom-out': ZoomOut,
    'rotate-cw': RotateCw,
    'rotate-ccw': RotateCcw,
    'flip-h': FlipHorizontal,
    'flip-v': FlipVertical,
    'layers': Layers,
    'box': Box,
    'circle': Circle,
    'square': Square,
    'triangle': Triangle,
    'hexagon': Hexagon,
    'octagon': Octagon,
    'piggy-bank': PiggyBank,
    'banknote': Banknote,
    'coins': Coins,
    'calculator': Calculator,
    'contact': Contact,
    'handshake': Handshake,
    'thumbs-up': ThumbsUp,
    'thumbs-down': ThumbsDown,
};

// Icon component props
export interface IconProps extends Omit<React.SVGProps<SVGSVGElement>, 'name'> {
    name: IconName;
    size?: number | 12 | 14 | 16 | 20 | 24 | 32;
    className?: string;
}

// Main Icon component using name-based lookup
export const Icon: React.FC<IconProps> = ({
    name,
    size = 16,
    className = '',
    ...props
}) => {
    const LucideIcon = ICONS[name] ?? Info;
    return (
        <LucideIcon
            size={size}
            strokeWidth={1.8}
            className={`inline-block align-middle shrink-0 ${className}`}
            {...props}
        />
    );
};

// Alternative: Direct icon component usage (for backwards compatibility)
export interface DirectIconProps {
    icon: LucideIcon;
    size?: number;
    className?: string;
}

export const DirectIcon: React.FC<DirectIconProps> = ({
    icon: IconCmp,
    size = 16,
    className = '',
}) => {
    return (
        <IconCmp
            size={size}
            strokeWidth={1.8}
            className={`inline-block align-middle shrink-0 ${className}`}
        />
    );
};

export default Icon;
